# $Id: Makefile,v 1.4 2010/08/24 11:54:53 aehlig Exp $

PORTVERSION=3.2
PORTNAME=rvc
PORTREVISION=1

MASTER_SITE=http://www.linta.de/~aehlig/
MASTER_SITE_SUBDIR= ${PORTNAME}
DISTFILES=${PORTNAME}-${PORTVERSION}.tgz
TAR_PARAMETER=z

CONFIGURE_CMD=true # don't configure

include ../ports.mk
