# $Id: Makefile,v 1.4 2010/07/14 07:35:02 aehlig Exp $

PORTVERSION=1.07
PORTNAME=uucp
PORTREVISION=2

MASTER_SITE=http://ftp.gnu.org/pub/gnu/
MASTER_SITE_SUBDIR= ${PORTNAME}
DISTFILES=${PORTNAME}-${PORTVERSION}.tar.gz
TAR_PARAMETER=z

CONFIGURE_OPTIONS= --with-newconfigdir=/etc/uucp

include ../ports.mk
