# $Id: Makefile,v 1.1 2010/04/20 14:38:30 aehlig Exp $

PORTVERSION=2.7.1
PORTNAME=libxml2

MASTER_SITE=http://xmlsoft.org/
MASTER_SITE_SUBDIR= sources/old
DISTFILES=${PORTNAME}-sources-${PORTVERSION}.tar.gz
TAR_PARAMETER=z

include ../ports.mk
