# $Id: Makefile,v 1.2 2013/05/01 19:46:51 aehlig Exp $

PORTNAME=textreadutils
PORTVERSION=1.1

MASTER_SITE=http://www.linta.de/~aehlig/university/
DISTFILES=${PORTNAME}-${PORTVERSION}.tar.gz
TAR_PARAMTER=z

CONFIGURE_CMD=true # no configure

include ../ports.mk
