# $Id: Makefile,v 1.1 2011/04/08 11:47:54 aehlig Exp $

PORTVERSION=1.8.6
PORTNAME=guile

MASTER_SITE=http://ftp.gnu.org/gnu/
MASTER_SITE_SUBDIR=guile
DISTFILES=${PORTNAME}-${PORTVERSION}.tar.gz
TAR_PARAMETER=z

include ../ports.mk
