PORTVERSION=2.0.22
PORTNAME=libevent

MASTER_SITE=http://downloads.sourceforge.net/project/levent/libevent/libevent-2.0/
DISTFILES=${PORTNAME}-${PORTVERSION}-stable.tar.gz
TAR_PARAMETER=z

WRKSRC=${WORKDIR}/${PORTNAME}-${PORTVERSION}-stable
FETCH_ARGS=--no-check-certificate

include ../ports.mk
