PORTVERSION=1.9a
PORTNAME=tmux

MASTER_SITE=http://downloads.sourceforge.net/project/tmux/tmux/tmux-1.9
DISTFILES=${PORTNAME}-${PORTVERSION}.tar.gz
TAR_PARAMETER=z

#EXTRABUILDENV = LDFLAGS="-L/usr/lib64/"

include ../ports.mk
