PORTVERSION=2.0
PORTNAME=tmux

MASTER_SITE=http://downloads.sourceforge.net/project/tmux/tmux/tmux-2.0
DISTFILES=${PORTNAME}-${PORTVERSION}.tar.gz
TAR_PARAMETER=z
FETCH_ARGS=

#EXTRABUILDENV = LDFLAGS="-L/usr/lib64/"

include ../ports.mk
