# $Id: Makefile,v 1.2 2012/07/16 19:38:56 aehlig Exp $

PORTNAME=units
PORTVERSION=2.00

MASTER_SITE=http://ftp.gnu.org/gnu/units/
DISTFILES=${PORTNAME}-${PORTVERSION}.tar.gz
TAR_PARAMTER=z

include ../ports.mk
