# $Id: Makefile,v 1.1 2011/04/08 11:47:55 aehlig Exp $

PORTVERSION=3.1
PORTNAME=libctl

MASTER_SITE=http://ab-initio.mit.edu/${PORTNAME}
DISTFILES=${PORTNAME}-${PORTVERSION}.tar.gz
TAR_PARAMETER=z

include ../ports.mk
