# $Id: Makefile,v 1.1 2010/04/20 14:38:30 aehlig Exp $

PORTVERSION=0.29.3
PORTNAME=neon

MASTER_SITE=http://www.webdav.org/
MASTER_SITE_SUBDIR= ${PORTNAME}
DISTFILES=${PORTNAME}-${PORTVERSION}.tar.gz
TAR_PARAMETER=z

CONFIGURE_OPTIONS= --with-ssl
 
include ../ports.mk
